### ISSUE TITLE
Can you add a new delegate method that is called when the on/off state changes?

### ISSUE THREAD

**Issue by Sweeper777** [lilei644/LLSwitch#1]
At the moment, I can only use the `didTapOnLLSwitch` method to detect a change in state. However, this is bad because:

If I have a LLSwitch that is originally on. And the user taps on it. The delegate method is called _before_ the state changes. So if I get the `on` property of the switch in the delegate method, I will get on, not off. This means that I need to reverse the Bool value to get the new on/off state.

That's just weird. If I come back after a few months I won't know what the `!` is doing there. This confuses people.

You see, the original `UISwitch` has a `ValueChanged` control event. Why not add such a delegate method to `LLSwitch`? It will look something like this:

```
func llSwitch(llSwitch: LLSwitch, didChangeValue value: Bool)
```

**Comment by lilei644** [comment]
Thank you for your attention！
You see you can use the following method to satisfy your requirements?
`- (void)animationDidStopForLLSwitch:(LLSwitch *)llSwitch {
    NSLog(@"stop --- staues:%hhd", llSwitch.on);
}`

**Comment by Sweeper777** [comment]
Yes, that works! Thanks! But can you rename it to `valueDidChange`? Because in most cases, people want to be notified when the value changes, not when the animation ends (although they are essentially the same thing). Rename it so that it can be more intuitive.

**Comment by lilei644** [comment]
Thank you for your advice！
I have added a new delegate,You can try it！
`- (void)valueDidChanged:(LLSwitch *)llSwitch on:(BOOL)on {
NSLog(@"stop --- on:%hhd", on);
}`
